sudo: required
services:
  - docker

before_install:
  - docker build -t pranov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pranov/react-test npm test

after_success:
  - docker build -t pranov/multi-client ./client
  - docker build -t pranov/multi-nginx ./nginx
  - docker build -t pranov/multi-server ./server
  - docker build -t pranov/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push pranov/multi-client
  - docker push pranov/multi-nginx
  - docker push pranov/multi-server
  - docker push pranov/multi-worker